### ISSUE TITLE
Switching from YouTube video to non-YouTube video fails

### ISSUE THREAD

**Issue by aktary** [NamPNQ/bower-videogular-youtube#21]
When loading the player, onVideoReady() sets the getter/setter functions and the play(), pause(), etc.  When changing to a non-YouTube source, these functions are never returned to their original (non-YouTube) state, so pressing play (for example) fails.

**Comment by joebell93** [comment]
Also experiencing this issue @NamPNQ.

Have you found a workaround @aktary?

**Comment by aktary** [comment]
No :(

The project got put on the back burner for a while... but it's  still an
issue that I'm going to have to tackle eventually.

Regards,

David Aktary

**Comment by joebell93** [comment]
I was hoping you weren't going to say that! I really need to get my project up and working ASAP.

I'll post an update if I find a temporary fix

**Comment by 2fdevs** [comment]
Hi guys,

We're talking with @NamPNQ to provide support to this plugin since it haves a lot of demand. I will try to make a PR to fix this in a few days, ok?

**Comment by joebell93** [comment]
@2fdevs fantastic, thank you!

**Comment by aktary** [comment]
Yes, thank you!  Just in time too... we're going to restart the project
soon and need this working!  :)

Regards,

David Aktary

**Comment by joebell93** [comment]
@2fdevs hey guys, do you have any news on this fix?

**Comment by 2fdevs** [comment]
I want to work on this issue this week. I hope to have something for the weekend.

**Comment by 2fdevs** [comment]
After playing a while with this I think that the best is not to fix this and offer a workaround.

The main problem here is with the Videogular API, which is using the media element to define states (playing, paused), time values (current time, duration) and other properties (like volume and so on).

The Youtube plugin is overriding the media element properties and I'm not able to retrieve the property again once it is overriden.

So my recommended workaround is to destroy the player (remove the tag) and add it again. Another workaround could be to have 2 players, one to play Youtube files and the other one to play regular files, and show the player that you want. I think that the first one is a better solution though.

This is a problem with the Videogular API itself, and I will take this into account for Videogular 2.0. Sorry guys, I know that a workaround is not always desirable.

**Comment by joebell93** [comment]
Thanks @2fdevs, is there any particular method you could recommend for removing the tag itself?

**Comment by 2fdevs** [comment]
Well, I have not tried it, but removing the tag with `parent.removeChild(elem);` and then you can use `$compile` to add again the player. For example:

```
angular.module("myApp").controller("myCtrl", ["$compile", "$scope", 
	function($compile, $scope) {
		var videoPlayer = '<videogular><vg-media vg-src="ctrl.srouces"></videogular>';
		var ytPlayer = '<videogular><vg-media vg-src="ctrl.srouces" vg-youtube="rel=1;showinfo=1"></videogular>';
		var container = angular.element(document.querySelector(".videogular-container"));

		// ... some code over here

		this.setYoutubeVideo = function() {
			var elem = angular.element(ytPlayer);
			var compiled = $compile(elem)($scope);

			container.append(elem);
		};

		this.setNormalVideo = function() {
			var elem = angular.element(videoPlayer);
			var compiled = $compile(elem)($scope);

			container.append(elem);
		};
	}]
);
```

**Comment by joebell93** [comment]
I appreciate your help, I'll give it a shot and keep you posted

**Comment by joebell93** [comment]
#### Update
I followed your solution (slightly) and I found the following works for now.
I'm using another array, "info",  as well as "sources", and this stores a value to determine the video's service amongst other details. So my code effectively checks to see when the service changes and then reloads the vg-media tag. 
It would probably be much simpler to just remove and append vg-media when the video starts, but this works for me at the moment.

I've also noticed that it doesn't really matter if `youtube="autoplay=1;"` is present or not .

This function gets called every time the video is set:
```javascript
var _this = this;
var loadPlayer = '<vg-media vg-src="controller.config.sources" class="videogular-container" vg-youtube="autoplay=1;"></vg-media>';

_this.setPlayer = function() {
    var elem = angular.element(loadPlayer);
    var compiled = $compile(elem)($scope);
    angular.element(document.querySelector("vg-media")).remove();
    angular.element(document.querySelector(".vg-media-container")).append(elem);

};
```

Thanks again @2fdevs. If you're interested in seeing more of my project, please check out [@mixamu](https://twitter.com/mixamu). If all goes to plan, I'll be tweeting beta information within the next 2-3 weeks.

**Comment by 2fdevs** [comment]
Good to know!!

I will check Mixamu, seems really interesting :)

Actually, I want to create a showcase gallery in Videogular website, so if I finally do that I will add it, for sure :)

Closing!

**Comment by keckelt** [comment]
That looks cool, similar to what i want to achieve :)

How did you realize the scrub bar?

**Comment by Fendy83** [comment]
The solution from joebell93  worked for me! Thanks!
