### ISSUE TITLE
Auto play not working

### ISSUE THREAD

**Issue by johnzw89** [NamPNQ/bower-videogular-youtube#27]
I started with the example youtube.js and html files and the video does not auto play.  Here is my code:

  $scope.onPlayerReady = function (API) {
      $scope.API = API;
      ytplayer.playVideo();
    };

    $scope.onCompleteVideo = function () {
      $scope.isCompleted = true;
    };

    $scope.onUpdateState = function (state) {
      $scope.state = state;
    };

    $scope.onUpdateTime = function (currentTime, totalTime) {
      $scope.currentTime = currentTime;
      $scope.totalTime = totalTime;
    };

    $scope.onUpdateVolume = function (newVol) {
      $scope.volume = newVol;
    };

    $scope.videos = [
      {
        sources: [
        	{src: video.url_source}
        ]
        // Tracks are inside .mpd file and added by Dash.js
      }
    ];

	$scope.config = {
      autoHide: true,
      autoHideTime: 3000,
      autoPlay: true,
      sources: $scope.videos[0].sources,
      tracks: $scope.videos[0].tracks,
      loop: true,
      preload: "auto",
      transclude: true
  };

**Comment by joebell93** [comment]
Also experiencing this issue

**Comment by joebell93** [comment]
Also experiencing this issue but I feel I may have found a fix.

In youtube.js, change your playerVars to the following:

    playerVars = {
        'controls': 0,
        'showinfo': 0,
        'rel': 0,
        'autoplay': 1
    };

**Comment by johnzw89** [comment]
@joebell93 
thanks that worked.  Although I had to do without quotes:

playerVars = {
    controls: 0,
    showinfo: 0,
    rel: 0,
    autoplay: 1
};

However now I find that the videogular $API.currentState is not in sync with the youtube state...

**Comment by joebell93** [comment]
@johnzw89 I'm getting the same unfortunately, I'd only suggest it as a temporary workaround.
Out of interest, are you using playlists? I'm having a lot of trouble with the YouTube video ending and not reverting back to a standard videogular media object to continue on with the playlist (this is before and after I added the autoplay value).

**Comment by johnzw89** [comment]
@joebell93 I am not using playlists yet.  There's a separate discussion which might benefit you here:
https://github.com/NamPNQ/bower-videogular-youtube/issues/30

**Comment by keckelt** [comment]
I Already made a pull request, which was already merged as far as I
remember.
You might want to load the plugin directly from github with bower.
Am 15.04.2015 21:42 schrieb "John Wei" <notifications@github.com>:

**Comment by joebell93** [comment]
@keckelt I just loaded the plugin directly from GitHub but unfortunately the video still doesn't play automatically unless I add the playerVars value

**Comment by keckelt** [comment]
Yeah, i didn't add that, but the States should update as expected (at least they do in my project).

**Comment by 2fdevs** [comment]
Merged PR. Closing.
