### ISSUE TITLE
Clicking VIdeo to Play/Pause doesn't trigger an event

### ISSUE THREAD

**Issue by keckelt** [NamPNQ/bower-videogular-youtube#30]
Hi,
playing or pausing the video by simply clicking on it doesn't trigger a state change event.

my Videogular HTML looks like this:
````html
<videogular vg-player-ready="controller.onPlayerReady($API)"  vg-update-time="controller.onUpdateTime($currentTime, $duration)" vg-update-state="controller.onUpdateState($state)" vg-complete="controller.onCompleteVideo()" vg-theme="controller.config.theme">
  <vg-media vg-youtube="rel=1;showinfo=1" vg-src="controller.config.sources"></vg-media>
</videogular>
````

and the controller's onComplete function is just:
````javacript
controller.onCompleteVideo = function() {
  console.log("onCompleteVideo");
};
````

**Comment by arminhammer** [comment]
I just tested this out and I can confirm that it works.  I now have onCompleteVideo() executed after the video is done playing.  I recommend merging this fix.

**Comment by NamPNQ** [comment]
@keckelt can you help me for continue maintaince this project, i don't have time for this.

**Comment by keckelt** [comment]
I'm currently working on my first angularjs application, so I only have
little knowledge here and none about bower and so on.
I guess it's best if I just continue to create pull request when I discover
any issues(?).

Best,
Klaus
Am 12.03.2015 06:33 schrieb "Phạm Ngọc Quang Nam" <notifications@github.com

**Comment by NamPNQ** [comment]
ok, tks you :dancer:
