### ISSUE TITLE
 videogular-youtube - Cannot read property '0' of undefined - onSourceChange(newVal[0].src);

### ISSUE THREAD

**Issue by mmichaelbiz** [NamPNQ/bower-videogular-youtube#33]
I have installed videogular-youtube and am faced with the following: 
```
TypeError: Cannot read property '0' of undefined
    at Object.fn (vg-youtube.js:121)
    at Scope.$get.Scope.$digest (angular.js:14308)
    at angular.js:14505
    at completeOutstandingRequest (angular.js:4924)
    at angular.js:5312
```

Note I have even used just the example files provided, (with modification include the correct css file for the theme) but still the same.

I have also tried with code from the latest commits and from the pull requests but faced with the same.

I am using the latest stable versions of angular and videogular.

Is videogular-youtube up to date?

**Comment by mmichaelbiz** [comment]
Issue was due to using outdated videogular tags. Seems like it works nicely when using vg-media and not vg-video as per the demo templates.

**Comment by philippeluickx** [comment]
+1, thanks for the info!

**Comment by JamesBaxta** [comment]
This doesn't work, using the vg-media tags lets me play videos but if I have a youtube url and regular video link it breaks after changing sources and playing the videos.

**Comment by mmichaelbiz** [comment]
@JamesBaxta, are you getting the same error as in this issue? 

What you are describing sounds more like issue #19 which is linked to pull #20.

Could you post here your config and error?

**Comment by 2fdevs** [comment]
Docs updated.

Closing this.
