### ISSUE TITLE
Vimeo support?

### ISSUE THREAD

**Issue by philippeluickx** [NamPNQ/bower-videogular-youtube#35]
Hey!

Thanks for a great plugin!
Any ambition for including Vimeo as well?

Cheers!

**Comment by keckelt** [comment]
Guess not, as you might see in the videogular issues.
I thought about maybe creating one, but I won't start until the end of the
current semester (summer) .
Am 24.04.2015 11:28 schrieb "Philippe Luickx" <notifications@github.com>:

Hey!

Thanks for a great plugin!
Any ambition for including Vimeo as well?

Cheers!

—
Reply to this email directly or view it on GitHub
<https://github.com/NamPNQ/bower-videogular-youtube/issues/35>.

**Comment by philippeluickx** [comment]
Allright, thanks for the info!

**Comment by bagabont** [comment]
You can check this project: [https://github.com/bagabont/videogular-vimeo](https://github.com/bagabont/videogular-vimeo). Still a rough implementation, but any help is welcome.

**Comment by philippeluickx** [comment]
Awesome, thanks!
