### ISSUE TITLE
the plguin not works! wey

### ISSUE THREAD

**Issue by enlacee** [NamPNQ/bower-videogular-youtube#36]
ERROR with there plugin...
the error is ?

![error](http://i57.tinypic.com/ri8879.png)

**Comment by 2fdevs** [comment]
Seems that you need to inject some dependencies. Could you paste the entire error stack trace?

**Comment by enlacee** [comment]
Hey 2fdvs, You could create the demo in your repo or in  http://codepen.io/

**Comment by NamPNQ** [comment]
@enlacee: We have `example` folder, are you try it?

**Comment by enlacee** [comment]
Yes, but there only stay a section html no works when open in http://localhost/example/youtube.html
it would usefull if the code work in http://codepen.io/ (it's more visual) thanks for answers @NamPNQ

**Comment by NamPNQ** [comment]
@enlacee: You need clone videogular, and put file `youtube.js` in example to `app/scripts/controllers`, and file `youtube.html` to `app/views`, and need make some edit in `index.html` for work. I think u very lazy

**Comment by enlacee** [comment]
thanks @NamPNQ  i'll try
