### ISSUE TITLE
Close ads

### ISSUE THREAD

**Issue by koz1ma** [NamPNQ/bower-videogular-youtube#39]
Hi,
When i use this plugin and youtube shows an ads popup( in the bottom of the video), i can't close this ads popup(the x button is disabled). There is a way i can enable this button or a function to close the ads?

Thanks

**Comment by 2fdevs** [comment]
Maybe there's a layer over the ad, could you try with right-click -> inspect element and take a look if it's an element over the ad?

**Comment by koz1ma** [comment]
When i inspect the element he points me to the <vg-poster> tag.

**Comment by 2fdevs** [comment]
Could you please post your example?

I want to take a look to it.

**Comment by koz1ma** [comment]
![ads](https://cloud.githubusercontent.com/assets/1053230/8600763/85ddf690-261c-11e5-86aa-95f278e36ec9.jpg)

**Comment by 2fdevs** [comment]
Probably is the poster, could you try removing the poster and trying to close again the ad?

**Comment by koz1ma** [comment]
it was the poster. I removed it and now i can close the ads. Thanks

**Comment by 2fdevs** [comment]
Maybe you can just add a css for vg-poster. Something like

    vg-poster { pointer-events: none; }

It should work and vg-poster doesn't need mouse events at all.

**Comment by koz1ma** [comment]
pointer-events: none solved the problem with poster. Thanks for the support.

**Comment by keckelt** [comment]
If the vg-poster doesn't need mouse events, dou you have an argument against adding (or let add) this ?

**Comment by 2fdevs** [comment]
@keckelt I think you're right, probably `vg-poster` should have `pointer-events: none` by default and if someone wants to interact with it can just activate it by overriding the css.
