### ISSUE TITLE
Not able to run with example in bower component

### ISSUE THREAD

**Issue by lakshaydulani** [NamPNQ/bower-videogular-youtube#43]
I have followed your example, but I am unable to run the youtube video.
Getting this error : TypeError: Cannot read property '0' of undefined

**Comment by NamPNQ** [comment]
@lakshaydulani Can you tell we more detail about error?

**Comment by lakshaydulani** [comment]
Here it is..
![screenshot from 2015-08-31 15 51 53](https://cloud.githubusercontent.com/assets/1629056/9576730/3caf1228-4ff8-11e5-9819-dbb9697e9646.png)

**Comment by lakshaydulani** [comment]
Can you please provide me with a jsfiddle?

**Comment by lakshaydulani** [comment]
Hi can you please provide a working example or jsfiddle.. m stuck with the youtube one

**Comment by 2fdevs** [comment]
Demo: http://codepen.io/2fdevs/pen/qOBRpO

I will add it to the readme.
