### ISSUE TITLE
if i play non-youtube video after youtube video then it gives me error TypeError: Cannot read property 'src' of null

### ISSUE THREAD

**Issue by sankesh** [NamPNQ/bower-videogular-youtube#44]
![image](https://cloud.githubusercontent.com/assets/14012840/9681368/2c338f20-531b-11e5-908b-3b7b64b3eebb.png)

**Comment by Fendy83** [comment]
I have the same issue...

**Comment by timt00** [comment]
I have this issue as well.

**Comment by NamPNQ** [comment]
See #21, need workaround

**Comment by Fendy83** [comment]
Thanks, I was able to solve my problem following the workaround!

**Comment by 2fdevs** [comment]
Great!
