### ISSUE TITLE
When changing source, the next video starts playing automatically

### ISSUE THREAD

**Issue by hassankhan** [NamPNQ/bower-videogular-youtube#48]
Every time I change the `sources` property, the video automatically starts playing - is there any way to stop this from happening?

**Comment by hassankhan** [comment]
As far as I can tell, it's because the `onSourceChange()` method calls the `initYoutubePlayer()` method, which finally calls the `loadVideoById()` method on the YouTube player. Could this be changed to `cueVideoById()` instead?

**Comment by hassankhan** [comment]
https://github.com/NamPNQ/bower-videogular-youtube/pull/49

**Comment by Elecash** [comment]
Looks good, I'll merge it, thank you! :)

**Comment by hassankhan** [comment]
Thanks :)
