### ISSUE TITLE
ytplayer.a is undefined

### ISSUE THREAD

**Issue by ersensen** [NamPNQ/bower-videogular-youtube#50]
Hi,

I am trying the plugin and getting error here;

                            API.mediaElement[0].__defineGetter__("videoWidth", function () {
                                return ytplayer.a.width; --<<<<  ytplayer.a is undefined
                            });

inspecting ytplayer from developer tools i cannot see the property "a"

**Comment by NamPNQ** [comment]
@ersensen I will take time to see this bug, thanks

**Comment by NamPNQ** [comment]
@ersensen I had check ![demo ](http://codepen.io/2fdevs/full/qOBRpO/) worked both in chrome and firefox, what is your browser?
