### ISSUE TITLE
How to display subtitle?

### ISSUE THREAD

**Issue by tuanbs** [NamPNQ/bower-videogular-youtube#59]
Hi, could you tell me how to display my own subtitle on youtube video. I tried this:

In html file I added: "...vg-tracks="config.tracks"...", and in js file I added: 
tracks: [
                    {                        
                        src: $scope.story.subtitleUrl,
                        kind: "subtitles",
                        srclang: "en",
                        label: "English",
                        default: "default"
                    }
        ]
But the subtitle is not shown. Thanks.

**Comment by NamPNQ** [comment]
Can you provide me a codepen

**Comment by tuanbs** [comment]
Hi, I cannot create Codepen account using Facebook.
Basically, I just added the tracks property to load the subtitle and using vg-tracks to show. If you still cannot figure it out, could you please give me a codepen example of using videogular-youtube displaying subtitle? Thanks.

**Comment by NamPNQ** [comment]
@tuanbs Oops, as i remember, u can do that, because vgtrack use native subtitle of video tag, and this is a reason it don't work like you want

**Comment by tuanbs** [comment]
Ok. I'll create an issue with @2fdevs . Thanks for your reply.
FYI, this is the codepen: http://codepen.io/tuanbs/pen/oxmwBv
